# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_auto_20160719_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='id_materia',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombres',
            field=models.CharField(max_length=30),
        ),
    ]
